In [1]:
import numpy as np 

**Scalars**

In [2]:
s = np.array(5)
s

array(5)

In [3]:
s.shape

()

In [4]:
x = s + 3
x

8

**Vectors**

In [5]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [6]:
v.shape

(3,)

In [7]:
x = v[1]
x

2

In [8]:
v[1:]

array([2, 3])

**Matrices**

In [9]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
m.shape

(3, 3)

In [11]:
m[1][2]

6

**Tensors**

In [12]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [13]:
t.shape

(3, 3, 2, 1)

In [14]:
t[2][1][1][0]

16

**Changing Shapes**

In [15]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [16]:
v.shape

(4,)

In [17]:
x = v.reshape(1,4)
x

array([[1, 2, 3, 4]])

In [18]:
x.shape

(1, 4)

In [19]:
x = v.reshape(4,1)
x

array([[1],
       [2],
       [3],
       [4]])

In [20]:
x.shape

(4, 1)

In [21]:
x = v[None, :]
x

array([[1, 2, 3, 4]])

In [22]:
x.shape

(1, 4)

In [23]:
x = v[:, None]
x

array([[1],
       [2],
       [3],
       [4]])

In [24]:
x.shape

(4, 1)