In [1]:
import numpy as np

**The Python way**

In [2]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
values

[6, 7, 8, 9, 10]

**The Numpy way**

In [3]:
values = [1,2,3,4,5]
values = np.array(values) + 5
values

array([ 6,  7,  8,  9, 10])

In [4]:
values += 5
values

array([11, 12, 13, 14, 15])

In [5]:
x = np.multiply(values, 5)
x

array([55, 60, 65, 70, 75])

In [6]:
x = values * 5
x

array([55, 60, 65, 70, 75])

In [7]:
values *= 0
values

array([0, 0, 0, 0, 0])

**Element-wise Matrix Operations**

Compatible Shapes

In [8]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [9]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [10]:
a + b

array([[ 3,  7],
       [11, 15]])

Incompatible Shapes

In [11]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [12]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c

array([[2, 3, 6],
       [4, 5, 9],
       [1, 8, 7]])

In [13]:
a.shape

(2, 2)

In [14]:
c.shape

(3, 3)

In [15]:
a + c

ValueError: ignored